//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppointmentsystemEntities : DbContext
    {
        public AppointmentsystemEntities()
            : base("name=AppointmentsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FitnessSchedule> FitnessSchedule { get; set; }
        public DbSet<FitnessTrainingSessions> FitnessTrainingSessions { get; set; }
        public DbSet<Instructor> Instructor { get; set; }
        public DbSet<ParticipantFeedback> ParticipantFeedback { get; set; }
        public DbSet<Participants> Participants { get; set; }
        public DbSet<PaymentTransactions> PaymentTransactions { get; set; }
    }
}
