//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitnessTrainingSessions
    {
        public FitnessTrainingSessions()
        {
            this.FitnessSchedule = new HashSet<FitnessSchedule>();
            this.ParticipantFeedback = new HashSet<ParticipantFeedback>();
            this.PaymentTransactions = new HashSet<PaymentTransactions>();
        }
    
        public int Sesssion_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> instructor_id { get; set; }
        public string locationn { get; set; }
        public Nullable<int> duration_minutes { get; set; }
        public string activity_type { get; set; }
        public string notes { get; set; }
    
        public virtual ICollection<FitnessSchedule> FitnessSchedule { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual ICollection<ParticipantFeedback> ParticipantFeedback { get; set; }
        public virtual ICollection<PaymentTransactions> PaymentTransactions { get; set; }
    }
}
