//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitnessSchedule
    {
        public int schedule_id { get; set; }
        public Nullable<int> instructor_id { get; set; }
        public Nullable<int> session_id { get; set; }
        public string day_of_week { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public string location { get; set; }
    
        public virtual FitnessTrainingSessions FitnessTrainingSessions { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
