//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.FitnessSchedule = new HashSet<FitnessSchedule>();
            this.FitnessTrainingSessions = new HashSet<FitnessTrainingSessions>();
        }
    
        public int instructor_id { get; set; }
        public string name_ins { get; set; }
        public string expertise { get; set; }
        public string contact_info { get; set; }
    
        public virtual ICollection<FitnessSchedule> FitnessSchedule { get; set; }
        public virtual ICollection<FitnessTrainingSessions> FitnessTrainingSessions { get; set; }
    }
}
