//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantFeedback
    {
        public int feedback_id { get; set; }
        public Nullable<int> session_id { get; set; }
        public Nullable<int> participant_id { get; set; }
        public Nullable<int> rating { get; set; }
        public string comments { get; set; }
    
        public virtual FitnessTrainingSessions FitnessTrainingSessions { get; set; }
        public virtual Participants Participants { get; set; }
    }
}
