//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public Participants()
        {
            this.ParticipantFeedback = new HashSet<ParticipantFeedback>();
            this.PaymentTransactions = new HashSet<PaymentTransactions>();
        }
    
        public int participant_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string contact_number { get; set; }
        public string address1 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
    
        public virtual ICollection<ParticipantFeedback> ParticipantFeedback { get; set; }
        public virtual ICollection<PaymentTransactions> PaymentTransactions { get; set; }
    }
}
