//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleId { get; set; }
        public string month { get; set; }
        public string day { get; set; }
        public Nullable<int> time { get; set; }
    }
}
