//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int trainingId { get; set; }
        public string trainingType { get; set; }
        public Nullable<int> locationId { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> instructorId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
