//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_allAppointment
    {
        public int instructorId { get; set; }
        public string Instructors_Name { get; set; }
        public string expertise { get; set; }
        public string contactNo { get; set; }
        public string Participants_Name { get; set; }
        public string userAddress { get; set; }
        public string userEmail { get; set; }
        public string userNumber { get; set; }
    }
}
