//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_adminUSER
    {
        public int User_Id { get; set; }
        public string Last_Name { get; set; }
        public string C_First_Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string userName { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
