//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CheckOut
    {
        public int checkoutID { get; set; }
        public string Cfname { get; set; }
        public string Clname { get; set; }
        public string Caddress { get; set; }
        public string Cemail { get; set; }
        public string Cphone { get; set; }
        public Nullable<System.DateTime> Cdatestart { get; set; }
        public Nullable<System.DateTime> Cdateexpire { get; set; }
        public Nullable<int> Cpayment { get; set; }
    }
}
