//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InsTable
    {
        public int Instructor_Id { get; set; }
        public string Name { get; set; }
        public string expertise { get; set; }
        public string contactNo { get; set; }
    }
}
