//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_INstaffBook
    {
        public string Instructor_Name { get; set; }
        public string Experties { get; set; }
        public string Contact_No_ { get; set; }
        public string Participant_Name { get; set; }
        public string Address { get; set; }
        public string Email_Add { get; set; }
        public string Phone_no_ { get; set; }
        public Nullable<System.DateTime> Date_Started { get; set; }
        public Nullable<System.DateTime> Date_Expiry { get; set; }
    }
}
