//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_System.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TrainingTable
    {
        public int Training_Id { get; set; }
        public string Training_Type { get; set; }
        public Nullable<int> Location_Id_ { get; set; }
        public Nullable<int> Duration_Time { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
